export const AUTH_ERROR = "AUTH_ERROR";

export const ALREADY_REG_EMAIL_ERROR = "ALREADY_REG_EMAIL_ERROR";
export const ALREADY_REG_NAME_ERROR = "ALREADY_REG_NAME_ERROR";

export const UNAUTH_USER_ERROR = "UNAUTH_USER_ERROR";

export const NONEXIST_LOBBY_ERROR = "NONEXIST_LOBBY_ERROR";
export const ALREADY_CONNECT_TO_LOBBY_ERROR = "ALREADY_CONNECT_TO_LOBBY_ERROR";
export const ALREADY_CONNECT_TO_DIFF_LOBBY_ERROR = "ALREADY_CONNECT_TO_DIFF_LOBBY_ERROR";
export const FULL_LOBBY_ERROR = "FULL_LOBBY_ERROR";