export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const LOGIN_OUT = "LOGIN_OUT";
export const AUTH_ERROR_CLEAN = "AUTH_ERROR_CLEAN";

export const REG_SUCCESS = "REG_SUCCESS";
export const REG_FAILED = "REG_FAILED";
export const REG_ERROR_CLEAN = "REG_ERROR_CLEAN";

export const LOBBIES_GET_SUCCESS = "LOBBIES_GET_SUCCESS";
export const LOBBIES_GET_ERROR = "LOBBIES_GET_ERROR";
export const LOBBIES_ERROR_CLEAN = "LOBBIES_ERROR_CLEAN";

export const CREATE_NEW_LOBBY_SUCCESS = "CREATE_NEW_LOBBY_SUCCESS";
export const CREATE_NEW_LOBBY_FAILED = "CREATE_NEW_LOBBY_FAILED";
export const CREATE_NEW_LOBBY_ERROR_CLEAN = "CREATE_NEW_LOBBY_ERROR_CLEAN";

export const LOBBY_CONN_GET_SUCCESS = "LOBBY_CONN_GET_SUCCESS";
export const LOBBY_GET_ERROR = "LOBBY_GET_ERROR";
export const LOBBY_ERROR_CLEAN = "LOBBY_ERROR_CLEAN";
export const LOBBY_CLEAN = "LOBBY_CLEAN";
export const LOBBY_CONN_WS_OPEN  = "LOBBY_CONN_WS_OPEN";
export const LOBBY_WS_PING_GET  = "LOBBY_CONN_WS_PING_GET";
export const LOBBY_WS_PING_SEND  = "LOBBY_CONN_WS_PING_SEND";
export const LOBBY_WS_PLAYER_READINESS_CHANGED = "LOBBY_WS_PLAYER_READINESS_CHANGED";
export const LOBBY_WS_START_GAME = "LOBBY_WS_START_GAME";
export const LOBBY_WS_LEAVE  = "LOBBY_WS_LEAVE";

export const GAME_GET_ERROR = "GAME_GET_ERROR";
export const GAME_ERROR_CLEAN = "GAME_ERROR_CLEAN";
export const GAME_CLEAN = "GAME_CLEAN";
export const CHANGE_GAME_PHASE = "CHANGE_GAME_PHASE";
export const SETUP_MAP = "SETUP_MAP";
export const MOVE_ATTEMPT = 'MOVE_ATTEMPT';
export const TRY_PLACE_TRAP = "TRY_PLACE_TRAP";
export const SHOW_TRAP = "SHOW_TRAP";
export const FIELD_CLEAN = "FIELD_CLEAN";
export const ACTIVATE_TRAP = "ACTIVATE_TRAP";
export const REMOVE_TRAP = "REMOVE_TRAP";
export const FINISH_GAME = "FINISH_GAME";
export const DRAW_GAME = "DRAW_GAME";

export const SETUP_CHARS = "SETUP_CHARS";
export const MOVE_CHAR = "MOVE_CHAR";
export const KILL_CHAR = "KILL_CHAR";
export const CLEAN_CHARS = "CLEAN_CHARS";

export const SETUP_TRAPS = "SETUP_TRAPS";
export const CHOOSE_TRAP = "CHOOSE_TRAP";
export const CLEAR_CHOSEN = "CLEAR_CHOSEN";